//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4959
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PracticeTeachingManagementSystem_Student.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.254.129.50;Initial Catalog=PhongMayThucHanh;User ID=sa;Password=1" +
            "23")]
        public string PhongMayThucHanhConnectionString {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=DONHAN-PC;Initial Catalog=PhongMayThucHanh;User ID=nhan;Password=123")]
        public string PhongMayThucHanhConnectionString1 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.107;Initial Catalog=PhongMayThucHanh;User ID=nhan;Password=" +
            "123")]
        public string PhongMayThucHanhConnectionString2 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.111;Initial Catalog=PhongMayThucHanh;Persist Security Info=" +
            "True;User ID=nhan;Password=123")]
        public string PhongMayThucHanhConnectionString3 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.254.129.50;Initial Catalog=PhongMayThucHanh;Persist Security Info" +
            "=True;User ID=sa;Password=123")]
        public string PhongMayThucHanhConnectionString4 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.107;Initial Catalog=PhongMayThucHanh;Persist Security Info=" +
            "True;User ID=nhan;Password=123")]
        public string PhongMayThucHanhConnectionString5 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=PhongMayThucHanh;User ID=sa;Password=123")]
        public string PhongMayThucHanhConnectionString6 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.1.102;Initial Catalog=PhongMayThucHanh;User ID=sa;Password=12" +
            "3")]
        public string PhongMayThucHanhConnectionString7 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=PhongMayThucHanh;User ID=sa;Password=123")]
        public string PhongMayThucHanhConnectionString8 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=PhongMayThucHanh;Persist Security Info=True" +
            ";User ID=sa;Password=123")]
        public string PhongMayThucHanhConnectionString9 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=PhongMayThucHanh;Persist Security Info=True" +
            ";User ID=sa;Password=123")]
        public string PhongMayThucHanhConnectionString10 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=169.254.60.17;Initial Catalog=PhongMayThucHanh;User ID=sa;Password=12" +
            "3")]
        public string PhongMayThucHanhConnectionString11 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=127.0.0.1;Initial Catalog=PhongMayThucHanh;User ID=sa;Password=123")]
        public string PhongMayThucHanhConnectionString12 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XUANHAU-PC\\SQLEXPRESS;Initial Catalog=PhongMayThucHanh;Integrated Sec" +
            "urity=True")]
        public string PhongMayThucHanhConnectionString13 {
            get {
                return ((string)(this["PhongMayThucHanhConnectionString13"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=XUANHAU-PC\\SQLEXPRESS;Initial Catalog=PTMS;Integrated Security=True")]
        public string PTMSConnectionString {
            get {
                return ((string)(this["PTMSConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BOVITHEHIEN-PC\\;Initial Catalog=PTMS;Persist Security Info=True;User " +
            "ID=sa;Password=123")]
        public string PTMSConnectionString1 {
            get {
                return ((string)(this["PTMSConnectionString1"]));
            }
        }
    }
}
